# Generated by Django 6.0.3 on 2026-03-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="active_tasks_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="experience_years",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
