# Generated by Django 6.0.3 on 2026-03-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_active_tasks_count_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["department"], name="accounts_us_departm_4298b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["experience_years"], name="accounts_us_experie_a88d5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["location"], name="accounts_us_locatio_8f6a57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["active_tasks_count"], name="accounts_us_active__6ee55e_idx"
            ),
        ),
    ]
