# Generated by Django 5.2.3 on 2026-03-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_taskassignment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
