# Generated by Django 6.0.3 on 2026-03-14 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=50)),
                ("min_experience", models.IntegerField()),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("max_active_tasks", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["department"], name="rules_taskr_departm_198fa6_idx"
                    ),
                    models.Index(
                        fields=["min_experience"], name="rules_taskr_min_exp_ada546_idx"
                    ),
                ],
            },
        ),
    ]
