# Generated by GPT-5.2 on 2026-03-16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0002_alter_taskrule_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrule",
            name="max_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskrule",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="taskrule",
            name="locations_allow",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="taskrule",
            name="locations_deny",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]

